#! /bin/bash
##-----------------------------------------------------------
##  自定义游戏控制脚本
##-----------------------------------------------------------

## erl路径
ERL='/root/erlang21_3/bin/erl'
ESCRIPT='/root/erlang21_3/bin/escript'

custom_ip()
{
    case `uname -n` in
    *)
         case `uname` in
               Linux)  LAN="eth0";;
               Darwin) LAN="en0";;
         esac
    esac
    IP=$(/sbin/ifconfig ${LAN}|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d 'addr:')
    ${ESCRIPT} ${RUNNING_DIR}/script/tool/get_server_ip.es $IP
}


custom_param()
{
    ## DUMP文件路径
    DATE=$(date "+%Y-%m-%d-%H%M%S")
    IP=$(custom_ip)
    LANG="default"
    PARAMS=" -setcookie ${ERLANG_COOKIE} "
    PARAMS="${PARAMS} -lang ${LANG} "
    if [ "${LANG}" != "default" ]; then
        PARAMS="${PARAMS} -pa ${SERVER_EBIN} ${SERVER_EBIN}/${LANG} "
    else
        PARAMS="${PARAMS} -pa ${SERVER_EBIN} "
    fi
    PARAMS="${PARAMS} -dge_root ${SERVER_DIR}/ "
    PARAMS="${PARAMS} -server_type  ${SERVER_TYPE} "
    PARAMS="${PARAMS} -smp enable "
    ## PARAMS="${PARAMS} +sub true "
    ## PARAMS="${PARAMS} -mnesia dump_log_write_threshold 100000 -mnesia no_table_loaders 100 -mnesia dump_log_update_in_place true -mnesia dir \\\"${DB_DIR}\\\" "
    ## PARAMS="${PARAMS} +K true +t 10485760 "
    PARAMS="${PARAMS} -env ERL_MAX_ETS_TABLES 500000  -env ERL_NO_VFORK 1  "
    ## PARAMS="${PARAMS} +sbt ${SBT_TYPE} "
    PARAMS="${PARAMS} -env ERL_CRASH_DUMP ${LOG_DIR}/erl_dump/${NODE_NAME}_${DATE}.erl_dump"
    PARAMS="${PARAMS} -kernel inet_dist_listen_min 20000 -kernel inet_dist_listen_max 30000 "
    PARAMS="${PARAMS}  +zdbbl 204800 "
    PARAMS="${PARAMS} -env CUSTOM_IP ${IP} "
    echo $PARAMS
}